### ISSUE TITLE
AFQ_SegmentFiberGroups

### ISSUE THREAD

**Issue by htakemur** [jyeatman/AFQ#4]
In AFQ_SegmentFiberGroups, line 249

 fp(ii,jj) = nanmean(p([fiberCoord:fiberCoord+fgLen(jj)-1]));

should be 
 fp(ii,jj) = nanmean(p([fiberCoord:fiberCoord+fgLen(jj)-1]),2);

because nanmean has the input on both matrix and dimension?

**Comment by jyeatman** [comment]
Thanks for the suggestion but I think p should always be a vector which means we don't need to specify the dimension. Are there cases when this is necessary?

**Comment by htakemur** [comment]
I got the error message here the last time, but I still did not find out why I got that error message. I will try to figure out about this; and will get back again if I think that this is general error.

**Comment by jyeatman** [comment]
One issue is to make sure the vistasoft nanmean rather than the spm nanmean
is being called. The spm version causes an error, so make sure the order is
correct in your path.

Jason D. Yeatman, PhD
Research Scientist
Institute for Learning and Brain Sciences (ILABS)
University of Washington
http://jasonyeatman.com

On Wed, May 20, 2015 at 2:41 AM, Hiromasa Takemura <notifications@github.com

**Comment by htakemur** [comment]
You are right. It turns out that I have loaded the SPM nanmean, not the vistasoft nanmean. 
I change the order, and now the error does not appear. 

Thank you!
